f1=open("abc.txt","w")
f1.write("my first file\n")
f1.write("-------------\n")
f1.write("I am Amritha\n")
f1.write("I am from mavelikara\n")
f1.write("Adress:kuttiyil padeettathil chunakkara naduvil chunakkara p.o\n")
f1=open("abc.txt",'r')
str=f1.read()
print("read string:",str)
f1.close()
print("file",f1.name,"closed")
